# The URL the site will be built for
base_url = "https://jx165-individual-project-1-378eec.gitlab.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "DeepThought"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
# Enable external libraries
katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        { url = "$BASE_URL/posts", name = "Posts" }
    ]},
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Jinglong Xiong"
avatar = "/images/me.jpg"

# Social links
[extra.social]
email = "timxjl2023@outlook.com"
linkedin = "jinglong-xiong"

# To add google analytics
[extra.analytics]
google = ""

# To add disqus comments
[extra.commenting]
disqus = ""

# To enable mapbox maps
[extra.mapbox]
enabled = false